# -*- coding: utf-8 -*-
"""Regresi Statistika

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1uNoCn17G-RWrfCf4arzyQmZ0xmxxepm4
"""

import pandas as pd
import numpy as np

# local import dataset
df = pd.read_csv('data.csv')
df.info()

# menghapus kolom "No" pada dataset
data = df.drop(columns=['No'])
data

X = df['Empati']
Y = df['Responsivitas']

# inisialisasi x_train dan y_train untuk pengujian model
x_train = X.values[:, np.newaxis]
y_train = Y.values

# inisialisasi model Linear Regresi
from sklearn.linear_model import LinearRegression
model = LinearRegression()
# training model
model.fit(x_train, y_train)

# uji coba testing model
x_test = [[7],[15]]
p = model.predict(x_test)
print('Prediksi model: ', p)

print('Coefficient: ', str(model.coef_))
print('Intercept: ', str(model.intercept_))

# grafik linear regresi dengan library matplotlib
from matplotlib import pyplot as plt
pb = model.predict(x_train)
dfc = pd.DataFrame({'Empati': X,'Responsivitas':pb})
plt.scatter(X,Y)
plt.plot(dfc['Empati'],dfc['Responsivitas'],color='r',linewidth=1)
plt.xlabel('Empati')
plt.ylabel('Responsivitas')
plt.show()

# uji akurasi model
from sklearn.preprocessing import StandardScaler
model.score(x_train, y_train)